In [1]:
%load_ext autoreload 
%matplotlib inline

In [2]:
import os
import cv2
import time
import torch
import torchvision
from torch import nn,optim
from torchvision import transforms

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
model = torch.load('0.8408566721581548.pth')

In [5]:
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=F

In [6]:
import cv2
import numpy as np
import torch.nn.functional as F

def process(images):
    images = cv2.resize(images,(224,224))
    images = transforms.ToPILImage()(images)
    images = transforms.ToTensor()(images)
    images = transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])(images)
    images = images.unsqueeze(0)
    images = images.type(torch.cuda.FloatTensor)
    return images

# 0:neg;1:pos

In [8]:
import pandas as pd
result = pd.DataFrame(pd.read_csv('detnet58_0.13_0.93.csv'))

In [10]:
import os
from tqdm import tqdm
counter = 0
pred_path = r'D:\\scripts\\crop_test_img\\pos'
# for i in tqdm(range(len(result))):
#     if(result['PredictionString'][i] == ' '):
for jpg in os.listdir(pred_path):
    path = pred_path + '\\'+ jpg
    images = cv2.imread(path)
    images = process(images)
    print(images.shape)
    break;
    outputs = model(images)
    pred = F.softmax(outputs)
    if(pred.type(torch.FloatTensor).detach().numpy()[0][0] > 0.90):
        counter = counter + 1 
        print(pred)
        print(jpg)
print('{:d}'.format(counter))
#         filename = jpg.split(' ')
#         name = filename[0]
#         x_coor = filename[1].split('.')[0] + '.' + filename[1].split('.')[1]
#         print(name)
#         print(type(x_coor))
#         current_df  = result[result['patientId'] == name]
#         pred_str_list = list(current_df['PredictionString'])[0].split(' ')
#         for j in range(int(len(pred_str_list)/5)):
#             if(pred_str_list[1 + j*5] == x_coor):
#                 pass
#         break;
    # _,predicted = torch.max(outputs.data,1)

torch.Size([1, 3, 224, 224])
0


In [70]:
pred.type(torch.FloatTensor).detach().numpy()[0][0]

0.12906794

In [69]:
num > 0.8

False

In [12]:
transform = transforms.Compose([
    transforms.Resize((224,224),2),
#     transforms.Resize(32),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

In [15]:
import pandas as pd

In [16]:
result = pd.DataFrame(pd.read_csv('detnet58_0.13_0.93.csv'))
_ = result[result['patientId'] == '000db696-cf54-4385-b10b-6b16fbb3f985']

In [39]:
temp = _['PredictionString']

In [45]:
stt = str(temp)

In [52]:
_

patientId  \
825  000db696-cf54-4385-b10b-6b16fbb3f985   

                                      PredictionString  
825  1.0 276.2061 288.65408 217.3351 470.24392 1.0 ...

In [118]:
ii = list(_['PredictionString'])

In [133]:
import copy
ii[0].split(' ')[6] = str(5)

patientId  \
825  000db696-cf54-4385-b10b-6b16fbb3f985   

                                      PredictionString  
825  1.0 276.2061 288.65408 217.3351 470.24392 1.0 ...

In [116]:
test = test.split(' ')

In [117]:
len(test)

10

In [118]:
result

patientId  \
0    285e0dd4-4f19-47ab-9ce0-6b02c1396f29   
1    2e951e03-086d-464d-87fa-bfab0e329721   
2    2bb1db95-73ad-46b0-8567-8a03d9a83def   
3    25e49cde-cdd9-47ba-9e3c-bc8406433240   
4    22da0004-e69d-49c5-bde5-252ab5895da0   
5    2b55eeed-3408-46fd-9e18-d7c5295a92b2   
6    00ddefb9-d94e-4e86-b945-970be30483d7   
7    1aa03e26-b635-47f9-bd58-8ed0a8e5fa50   
8    1325b50a-3e35-41a6-a871-40359dccf55e   
9    0f4c38f3-854f-4f74-9051-59c801a6c859   
10   28775c77-80e8-4f8c-be85-7a44162b5c28   
11   212ccee9-80ec-4d67-8edb-5959d344c923   
12   290e32e9-3632-4642-a1d4-70c975d376b7   
13   30d44656-0af9-4870-b43c-f83de6cd8f2e   
14   2f200e3f-8e4c-4675-948c-8226cd65163a   
15   21cca2a5-6cb9-4667-bde6-5fe4ac8d2a29   
16   2526df82-a04c-4aef-8df6-a48e3b4c6cde   
17   0d45f420-10d0-41a2-9b87-f5ea81c28599   
18   2ff18655-f28c-4992-a622-44300e071629   
19   03a9b990-18bb-4370-ac03-7fa385ea72bf   
20   2bbd1729-f918-4712-bdc7-691240c8636f   
21   0fcd4b17-359c-40bf-a21c-907d0a91b5df   
22   100d2b25-aba5-4502-bd2a-edeaa66fde00   
23   2ec88120-5cef-45a0-b9d6-629fdf99ab8c   
24   110f1696-ffba-439f-9918-1230c656121a   
25   2a740d72-0dc4-4439-93ed-60cad708d7c4   
26   c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8   
27   bfea966c-f72f-42f7-9712-9cf77b66bad6   
28   13cca55a-615f-4f7c-9061-7d12185baace   
29   119a9ba2-0785-4321-b074-dbfcffc5197e   
..                                    ...   
970  05632b7f-f4c5-4d67-aa93-8f3c04eb7937   
971  2bdfab0d-4192-4a7f-a366-587c379ecdba   
972  c0d8eb9f-8276-414b-8cbb-d8f28b61aac1   
973  2f9c1b97-74a7-4781-bad3-c46cc08c69c8   
974  01469010-0fab-4a07-86c6-962996ce2ca0   
975  02cfa7d1-61e0-4d9e-8664-9a7469ccab76   
976  1a9c2e64-7cbd-480c-9598-9de93b69d6b2   
977  20e1f3f2-953a-4a8e-b7d3-8db21a4ce933   
978  0ff5bf5b-6af7-4537-90d0-1c47058d0627   
979  1328013e-dca0-497b-9523-072bc6b23e17   
980  0ff01216-ce5b-44bd-a857-bc22dc9f8f3c   
981  2a54c3ee-7d7f-4c32-9b77-87279b8777a7   
982  0f526bd8-4383-4b59-8db0-7ed03e41c142   
983  2c7b3f02-3fe4-4d33-88d5-413fcf18b118   
984  c1f6b555-2eb1-4231-98f6-50a963976431   
985  14df3d5a-f3fd-4a64-ae75-5a9610575e11   
986  2118026e-ed2f-4d1e-baa2-0e9e1004f72c   
987  1e616583-e09d-476d-ac25-8fa620f4298a   
988  1c2fbe4f-6785-420d-a7ef-d81b84ff45ec   
989  c18d1138-ba74-4af5-af21-bdd4d2c96bb5   
990  0db60a41-2a6a-421b-a304-8799739eaec5   
991  1bc755ca-d22a-4a4f-9eb7-acc2e2b45b44   
992  00293de0-a530-41dc-9621-0b3def01d06d   
993  121eb744-2f28-443d-a361-ba0cb2401462   
994  27e7f64a-a6a4-4a36-8888-c6c96c8e7828   
995  c05d1108-641a-465c-9b56-b32bcb548bb3   
996  30ed2b9d-b832-4c0a-af4d-a6ccc70ef1b5   
997  243d4ffb-6f8d-48d4-aa86-e93dcbb7b238   
998  05905ac6-1b8f-4793-a7d2-ac794b1bb2ff   
999  2785e983-bdcb-4ece-8dc4-82b14d2d2b85   

                                      PredictionString  
0    1.0 573.59515 325.7581 206.71479 372.77266 1.0...  
1                                                       
2           1.0 241.9187 521.71075 175.09827 177.06925  
3                                                       
4                                                       
5    1.0 578.62946 458.53104 232.50833999999998 205...  
6                                                       
7                                                       
8                                                       
9                                                       
10   1.0 643.01605 404.56293 219.85185 228.21562999...  
11   1.0 249.62453 588.166 204.76475 175.2295999999999  
12   1.0 530.6036 309.87766 186.20690000000002 296....  
13   1.0 555.0067 126.6157 174.34894999999995 158.1...  
14   1.0 622.04987 133.6634 220.46587999999997 500....  
15   1.0 612.44507 594.026 225.82383000000004 199.5...  
16                                                      
17   1.0 300.3829 424.60806 221.49453999999997 382....  
18                                                      
19                                                      
20   1.0 664.78217 546.98615 202.00383 224.4

In [119]:
test_path = r'D:\\scripts\\kaggle-crModel\\jpg_test'
save_path = r'D:\\scripts\\crop_test_img\\pos'

In [120]:
name = result['patientId']

In [142]:
bbox = result['PredictionString']

In [146]:
x = bbox[bbox == ' ']

In [148]:
len(result)

1000

In [138]:
from tqdm import tqdm
for i in tqdm(range(len(result))):
    path = test_path + r'\\' + name[i] + r'.jpg'
    img = cv2.imread(path)
    box = bbox[i].split(' ')
#     print(len(box)/5)
    
    for j in range(int(len(box)/5)):
        x1,y1,width,height = box[j*5+1],box[j*5+2],box[j*5+3],box[j*5+4]
        x1 = float(x1)
        y1 = float(y1)
        width = float(width)
        height = float(height)
        x2 = x1 + width
        y2 = y1 + height
        img1 = img[int(y1):int(y2),int(x1):int(x2)]
        path1 = save_path + r'\\' + name[i] + ' ' +str(x1) + '.jpg'
        cv2.imwrite(path1,img1)

100%|██████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:13<00:00, 75.57it/s]


In [173]:
img1.shape

(191, 371, 3)

In [175]:
height

370.54227000000003

In [177]:
name[name == '000fe35a-2649-43d4-b027-e67796d412e0']

549    000fe35a-2649-43d4-b027-e67796d412e0
Name: patientId, dtype: object

In [178]:
bbox[549]

'1.0 83.62723 228.68242 292.94397 407.66853000000003 1.0 569.12164 278.57272 270.27656 385.19052'

In [81]:
def pre_process(images):
    images = cv2.resize(images,(224,224))
    images = np.transpose(images,(2,0,1))
    images = torch.from_numpy(images)
    images = images.unsqueeze(0)
    images = images.type(torch.cuda.FloatTensor)
    return images

In [184]:
import os
path = r'D:\scripts\crop_test_img'
for jpg in os.listdir(path):
    image = cv2.imread(path + r'\\' + jpg)
    image = pre_process(image)
    outputs = model(image)
    _,predicted = torch.max(outputs.data,1)
    predict_result.append(predicted)

In [185]:
predict_result

[tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor(

In [139]:
path = r'D:\\scripts\\crop_test_img\\'

In [140]:
transform = transforms.Compose([
    transforms.Resize((224,224),2),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

In [141]:
test_dataset = torchvision.datasets.ImageFolder(root = path, transform = transform)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=False)

In [279]:
test_dataset.imgs

[('D:\\\\scripts\\\\crop_test_img\\\\pos\\000db696-cf54-4385-b10b-6b16fbb3f985 276.2061.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\000db696-cf54-4385-b10b-6b16fbb3f985 605.87335.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\000fe35a-2649-43d4-b027-e67796d412e0 569.12164.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\000fe35a-2649-43d4-b027-e67796d412e0 83.62723.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\001916b8-3d30-4935-a5d1-8eaddb1646cd 170.41177.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\0022073f-cec8-42ec-ab5f-bc2314649235 576.61835.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\002cb550-2e31-42f1-a29d-fbc279977e71 161.14946.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\002cb550-2e31-42f1-a29d-fbc279977e71 488.93866.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\006e75c8-1fd9-4a5a-99e7-285addebed55 247.91495.jpg',
  0),
 ('D:\\\\scripts\\\\crop_test_img\\\\pos\\0087bd3a-55a7-4045-b111-b018fa52d361 243.26718.jpg'

In [151]:
predict = dict()
for i, data in enumerate(test_loader):
    inputs, labels = data        
#     inputs = pre_process(inputs)
#     inputs, labels = inputs, labels
#     images = np.transpose(images,(2,0,1))
#     images = torch.from_numpy(images)
#     images = images.unsqueeze(0)
    inputs = inputs.type(torch.cuda.FloatTensor)
    outputs = model(inputs)
    _, predicted = torch.max(outputs.data, 1)
    predict.update('')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

KeyboardInterrupt: 

In [143]:
list1

[tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor([ 0], device='cuda:0'),
 tensor([ 1], device='cuda:0'),
 tensor(

In [144]:
count = 0
for i in range(len(list1)):
    if(int(list1[i]) == 0):
        count = count + 1

In [158]:
test_loader.batch_sampler

In [166]:
import matplotlib.pyplot as plt
plt.imshow(inputs.cpu.data[4])

AttributeError: 'builtin_function_or_method' object has no attribute 'data'

In [184]:
labels[0]

tensor(0)